### ISSUE TITLE
Octopus Image Hides Nav Links When Resized

### ISSUE THREAD

**Issue by jdamiba** [pierretd/pierretd.github.io#1]
<img width="1220" alt="screen shot 2018-10-29 at 3 51 21 pm" src="https://user-images.githubusercontent.com/1557650/47676302-9ec1a880-db92-11e8-9ee5-7f3bfb99dbe3.png">
<img width="1440" alt="screen shot 2018-10-29 at 3 53 00 pm" src="https://user-images.githubusercontent.com/1557650/47676327-b862f000-db92-11e8-8a99-0a7cd87f51c7.png">
<img width="1440" alt="screen shot 2018-10-29 at 3 53 13 pm" src="https://user-images.githubusercontent.com/1557650/47676343-cc0e5680-db92-11e8-88f3-16d54bbe9eba.png">

**Comment by pierretd** [comment]
Thanks for opening this issue!  

I'll be looking into this. :flashlight:

I suspect the best solution is to configure the navbar to show the menu button unless the user is in full screen. 

If you have any better solutions I would love to hear them!
